### ISSUE TITLE
Epic: Batch viewer

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#1051]
**Description**

Add batch viewer.

**Additional resources**

Code by Felix https://codesandbox.io/s/fmsoz
Hosted app https://fmsoz.csb.app/
Example tx to try out https://etherscan.io/tx/0x837605365b931f5957aa11239d680dd051a0aacab9a80e5211f18e4d8438c752

It uses only public data + the tenderly API - no backend whatsoever.

**TO DO**
- [ ] Get a tenderly access token to be used with the project

**Feature breakdown**
It includes:
- [ ] Adapt code above to run on Explorer
- [ ] Add it to tx view

Good to have:
- [ ] Improve visualization / auto-sorting
- [ ] Use a different display library?
