### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by ramirotw** [gnosis/gp-ui#1065]
**Description**

<img width="979" alt="image" src="https://user-images.githubusercontent.com/3328006/158217757-9d539885-2e81-4412-bfc7-b2945dac0e72.png">

**Feature breakdown**
It includes:
- [ ] Volume chart UI (Use https://github.com/tradingview/lightweight-charts which is already a dependency)
- [ ] Stats cards UI
  <img width="411" alt="image" src="https://user-images.githubusercontent.com/3328006/158218487-81b3caaa-05dc-4559-8abb-155a0a8e1a96.png">
- [ ] Tokens table UI
  <img width="692" alt="image" src="https://user-images.githubusercontent.com/3328006/158218668-81178833-4f71-400a-8e67-07a164812f73.png">
- [ ] Integrate with cow-sdk

Good to have:
- [ ] First issue #1
- [ ] Another issue (#2)
