### ISSUE TITLE
[Theme] Setup theme framework

### ISSUE THREAD

**Issue by W3stside** [gnosis/gp-ui#18]
## Reorganise and Optimise Styles + Theme [Multipart PR]

This series of PRs will be to address our current `theme` + `styles` organisation and logic. It is built on top of the `styled-theming` we have all already seen in PR gnosis/gp-v1-ui#1626 but goes a bit further to clean up and make this more robust. It is similar to Uniswap's approach but incorporates other optimisations.

- [x] Add `polished` CSS interpolation library for easier CSS dynamic stylings gnosis/gp-v1-ui#1661 
- [x] Global styles: slim down / separate concerns, make two global style providers: Static and Themed gnosis/gp-v1-ui#1664 
- [x] Re-organise `styled` folder into `theme` > `styled` > root files gnosis/gp-v1-ui#1664 
- [x] Add custom ThemeProvider similar to Uniswap's approach that is strictly typed and maps children with `theme` prop gnosis/gp-v1-ui#1632 
- [x] Add hooks for dealing with app theme gnosis/gp-v1-ui#1667 
- [x] Add global state to save user app theme selections gnosis/gp-v1-ui#1667 
- [x] Upgrade `common/Buttons` logic to be more legible + easier to read w/code AND `types`
- [x] Fix `common/Buttons` stories
- [x] split `overrides.ts` into `overrides` folder and add each library we hack as a file

**Comment by anxolin** [comment]
can we close @W3stside ?

**Comment by W3stside** [comment]
@anxolin yes

**Comment by anxolin** [comment]
@W3stside thank you
