### ISSUE TITLE
[view meta tx] Simple page and main layout and mocked data

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#62]
# 🚨🚨🚨View order details

Requirements: 
- [ ] Allows to see the meta-transaction before is submitted in the settlement
  - [ ] Show all order fields
  - [x] Mock data on the page
- [ ] Search meta-transaction by ID
- [x] Open meta-transaction by URL
- [x] Status of the transaction: PENDING, EXECUTED, PARTIALLY_EXECUTED, EXPIRED, EXPIRED_PARTIALLY_EXECUTED?
- [ ] Link to settlement in the Explorer - if not PENDING nor EXPIRED
- [ ] Link to settlement transaction in Etherscan - if not PENDING nor EXPIRED

# Mockups 

https://www.figma.com/file/bEIQI9qESxqMVm5NkbtfZV/GP-Explorer-Wireframe-v1?node-id=1%3A6
(there's no detail view yet)

**Comment by anxolin** [comment]
@alfetopito we can close and remove the undone things (move to other issues)
