### ISSUE TITLE
Explorer: History of orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-ui#765]
**Description**

Display full history of orders by address

**Additional resources**

**Feature breakdown**
Pending/in progress:
- [x] Responsive Orders Table https://github.com/gnosis/gp-ui/issues/693
- [x] Search by address https://github.com/gnosis/gp-ui/issues/691
- [x] Deploy https://github.com/gnosis/gp-ui/issues/610

Follow up/good to have:
- [x] Horizontal scrollbar https://github.com/gnosis/gp-ui/issues/683 
- [x] Blinking table when empty https://github.com/gnosis/gp-ui/issues/684 
- [x] Improve amounts display https://github.com/gnosis/gp-ui/issues/629
- [x] Mkr token symbol not displayed https://github.com/gnosis/gp-ui/issues/555 / Bytes32 token name/symbol https://github.com/gnosis/gp-ui/issues/728 
- [x] Improve display of tokens with no symbol https://github.com/gnosis/gp-ui/issues/729
- [x] Internal links should re-use network https://github.com/gnosis/gp-ui/issues/747
- [x] Show tooltip under question icon https://github.com/gnosis/gp-ui/issues/722 
- [x] Display network indicator https://github.com/gnosis/gp-ui/issues/768
- [x] Search results under /search instead of /order https://github.com/gnosis/gp-ui/issues/767
- [x] Add loader for when orders are loading https://github.com/gnosis/gp-ui/issues/801
