### ISSUE TITLE
Explorer: Transaction viewer

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#780]
**Description**

Implement Transaction viewer page on Gnosis Protocol Explorer

First step towards batch view tool.

For now, we should only list all orders that were settled in a single blockchain transaction

**Additional resources**

New endpoint from backend returning all orders settled in a given transaction
https://protocol-rinkeby.dev.gnosisdev.com/api/#/default/get_api_v1_transactions__txHash__orders
`/api/v1/transactions/{txHash}/orders`

**Feature breakdown**
It includes:
- [x] Added page `/tx/<hash>` https://github.com/gnosis/gp-ui/issues/851
- [x] Design new page
- [x] Implement design (mocked, using storybook) https://github.com/gnosis/gp-ui/issues/852
- [x] Implement new backend API interface https://github.com/gnosis/gp-ui/issues/855
- [x] Wire up UI and backend data https://github.com/gnosis/gp-ui/issues/853
- [x] Search for transaction on search bar https://github.com/gnosis/gp-ui/issues/854

Good to have:
- [x] Search transaction on every network https://github.com/gnosis/gp-ui/issues/856
- [ ] Identify when tx is/is not a GPv2 transaction (offer link to blockexplorer) https://github.com/gnosis/gp-ui/issues/857

**Comment by alongoni** [comment]
Hey @alfetopito. Here is a first approach to the tx viewer:
![UI_Explorer v1  - TX viewer](https://user-images.githubusercontent.com/622217/142243079-dd2980e0-f540-48ad-8f94-4b83bf3c1dd0.png)

Should we need to add some relevant information from here?
![image](https://user-images.githubusercontent.com/622217/142243493-311b9214-bc08-474b-94a3-c2f47ab9eff7.png)

**Comment by alfetopito** [comment]
Thanks Agustin!

As I mentioned the other day in the meeting, we don't have right now a "list" of transactions from the contract.
This can be a next step and your UI fits great into that.

For now, a "detailed" transaction view is enough.

By that I mean a view that only shows a list of orders, for a single transaction. Basically the inner content, without search or pagination 
![screenshot_2021-11-17_13-32-31](https://user-images.githubusercontent.com/43217/142285804-e4a647a0-d2ec-4f6a-90ae-71860d1ad784.png)

And on top similar to orders
![screenshot_2021-11-17_13-33-59](https://user-images.githubusercontent.com/43217/142285956-61dc8188-bec6-409b-8e17-f5046423057f.png)
(It would say instead of `Order` -> `Transaction` details)
Also a link to etherscan to see the transaction there.

And as a next step we can expand and show the list of batches as you have suggested now

@biocom anything you'd like to add?

**Comment by alongoni** [comment]
Thanks @alfetopito. Design updated.
![UI_Explorer v1  - TX viewer](https://user-images.githubusercontent.com/622217/142461335-2f1a1b0f-0507-4631-8f91-b9d25dcf6e83.png)

**Comment by alfetopito** [comment]
Perfect @alongoni !

Unless anyone on @gnosis/gp-frontend has any comments, it's ready for implementation.

**Comment by anxolin** [comment]
It looks great, would it make sense to have some header with some basic information. In the future it could have the basic stats of the batch, like traded volume. Right now, it's easy to show the Tx hash, date, block number? (probably not), number of orders, number of different accounts, total fees, and list of involved tokens. 

However, probably we want to start without the header and reiterate later. Maybe even give a try to the graph :) 

Anyways, nice one! im looking forward for this feature

**Comment by alfetopito** [comment]
> Right now, it's easy to show the Tx hash, date, block number? (probably not), number of orders, number of different accounts, total fees, and list of involved tokens.

All of that seems pretty low effort fetched from the chain and would be great to have!

Still, I'd be happy to have just the simple version right now as it'll be a big plus.

So Agustin, you can work in parallel on Anxo's suggetion but the team is unblocked to start implementing the base version if there are resources available.
