### ISSUE TITLE
AppData / Affiliate Code

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#849]
**Description**

Affiliate code management

**Additional resources**
Reference for creating custom appData https://docs.google.com/document/d/1ryn3v4m7cXTTXfLfQX9xsRNYZ4PfSXhHVxjodkZHGzQ/edit#
Reference for addData encoded format https://docs.google.com/spreadsheets/d/16RzefdfpmEavl182h6iNEe7fRyAcaATCRYR0hMQ_734/edit#gid=209750149

**Feature breakdown**
It includes:
- [ ] Display affiliate data on order details page - only the hash
- [ ] Expandable optional are to display decoded affiliate data contents - fetched from IPFS

Good to have:
- [ ] Page to manage affiliate data
  - [ ] Able to decode appData directly similar to https://codepen.io/pacara/pen/BadZgjg
  - [ ] Able to create custom appData: Different appCode (other than `CowSwap`)

**Comment by alfetopito** [comment]
Now that SDK is integrating the encoding/decoding we'll be able to work on this
