### ISSUE TITLE
Explorer: Transaction viewer (pt2)

### ISSUE THREAD

**Issue by alfetopito** [gnosis/gp-ui#883]
**Description**

Follow up to https://github.com/gnosis/gp-ui/issues/780

While on that task a Tx/batch details view was added, on this task the goal is to show a list of txs

**Additional resources**

Design should be similar to Orders table, and not very far from Agustin's initial proposal https://github.com/gnosis/gp-ui/issues/780#issuecomment-971762144
![](https://user-images.githubusercontent.com/622217/142243079-dd2980e0-f540-48ad-8f94-4b83bf3c1dd0.png)

Except that the columns will not include order fields, but instead whatever can be fetched from the chain for each tx, such as:
- Tx time (derived from block time)
- Gas related info (minimum gas, gas price, etc)
- Whatever else might be relevant (the solver which submitted the tx)

**Feature breakdown**
It depends on:
- [ ] Network switcher #160 
- [ ] Contracts network aware #408 

It includes:
- [ ] Design txs page
- [ ] Implement component as storybook
- [ ] Implement handlers/hooks/api (whatever is relevant) to fetch contract events
- [ ] Wire up component and logic
- [ ] Pagination
- [ ] Update list on every new block (only if on the first page)

Good to have:
- [ ] <add anything I left out>
